#aseeva fourth task / preliminary review
AseevaIrina/junior-course-boilerplate pull request #4
Opened 2021-12-07 14:01 UTC by AseevaIrina

2021-12-09 08:40 UTC, vislogurov requested changes

2021-12-09 08:40 UTC, vislogurov commented on src/index.js
> +    this.setState(state => {
Вынеси эту логику в отдельный метод, это понадобится когда коснёмся мемоизации

2021-12-09 08:40 UTC, vislogurov commented on src/index.js
> +      filteredProducts: data
Почему data по дефолту? Изначально фильтры не применены, по идее тут пустой массив должен быть

2021-12-09 08:40 UTC, vislogurov commented on src/components/InputHendler/InputHandler.js
> +      event.target.value =  event.target.value.replace(/[^\d]/g,'');
Используй деструктуризацию `const { name, value} = event.target`

2021-12-09 14:29 UTC, AseevaIrina commented on src/components/InputHendler/InputHandler.js
> +      event.target.value =  event.target.value.replace(/[^\d]/g,'');
+

2021-12-13 07:00 UTC, vislogurov requested changes

2021-12-13 07:00 UTC, vislogurov commented on src/index.js
> +            discountValue={this.state.discount}
Используй деструктуризацию `const {discount, maxPrice итд} = this.state`

2021-12-13 07:00 UTC, vislogurov commented on src/index.js
> +const memoize = (fn) => {
Предлагаю создать директорию `utils` и все служебные функции хрнаить там. Они могут понадобиться ещё в других компонентах.

2021-12-13 07:00 UTC, vislogurov commented on src/components/ProductCard/ProductCard.js
> +    const{isInStock,img,title,price,maxRating,rating } = this.props
Сравни 
`const { inputMinValue, inputMaxValue, handleChangeState, discountValue } = this.props`
и
`const{isInStock,img,title,price,maxRating,rating } = this.props`

Какую запись приятнее читать?

2021-12-13 07:10 UTC, AseevaIrina commented on src/index.js
> +const memoize = (fn) => {
++

2021-12-13 07:11 UTC, vislogurov approved these changes

2021-12-17 08:32 UTC, merged